apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: debitos-tributarios-gitops-
  namespace: debitos-tributarios
spec:
  pipelineRef:
    name: debitos-tributarios-gitops
  taskRunTemplate:
    serviceAccountName: pipeline
  params:
    - name: git-url
      value: https://github.com/TiagoAvelino/debitos-tributarios-app.git
    - name: git-revision
      value: main
    - name: app-subdir
      value: .
    - name: helm-values-file
      value: helm/debitos-tributarios/values.yaml
    - name: image-namespace
      value: debitos-tributarios
    - name: image-name
      value: debitos-tributarios
    - name: audit-level
      value: high
    - name: enable-sonarqube
      value: "true"
    - name: sonar-host-url
      value: http://sonarqube:9000
    - name: sonar-project-key
      value: debitos-tributarios
    - name: sonar-token-secret-name
      value: sonarqube-token
    - name: sonar-token-secret-key
      value: token
    - name: git-user-name
      value: TiagoAvelino
    - name: git-user-email
      value: TiagoAvelino@users.noreply.github.com
    - name: argocd-server
      value: openshift-gitops-server.openshift-gitops.svc.cluster.local:443
    - name: argocd-application
      value: debitos-tributarios
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: github-basic-auth
